set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

"Bundle 'L9'
"Bundle 'FuzzyFinder'
Bundle 'https://github.com/kien/ctrlp.vim'
"Bundle 'https://github.com/yandy/vim-omnicppcomplete.git'
Bundle 'git://github.com/tpope/vim-surround.git'
Bundle 'AutoComplPop'
Bundle 'git://github.com/tpope/vim-fugitive.git'
Bundle 'git://github.com/vim-scripts/javacomplete.git'
Bundle 'git://github.com/Lokaltog/vim-powerline.git'
Bundle 'git://github.com/mikewest/vimroom.git'
Bundle 'https://github.com/Rip-Rip/clang_complete'
Bundle 'git://github.com/airblade/vim-gitgutter.git'

set ts=4
set hidden
set shiftwidth=4
set ai                  " auto indenting
set cindent
set history=100         " keep 100 lines of history
set ruler               " show the cursor position
syntax on               " syntax highlighting
set hlsearch            " highlight the last searched term

filetype plugin indent on

set rnu
set ignorecase

au BufEnter *.hs set expandtab
au BufEnter *.h set noexpandtab
au BufEnter *.c set noexpandtab
au BufEnter *.cpp set noexpandtab
au BufEnter *.py set noexpandtab
au BufEnter *.sh set noexpandtab
au BufEnter *.java set noexpandtab

au BufEnter *.h set omnifunc=ClangComplete
au BufEnter *.c set omnifunc=ClangComplete
au BufEnter *.cpp set omnifunc=ClangComplete

au BufEnter *.rb set expandtab
au BufEnter *.rb set smartindent
au BufEnter *.rb set ts=2
au BufEnter *.rb set sw=2
au BufEnter *.rb set softtabstop

if has("gui_running")
	colorscheme sonofobsidian
else
	colorscheme 256-grayvim
endif
set guifont=ProggyCleanTT\ 12.5
 
"map <F12> :!ctags -R --sort=yes --c++-kinds=+p --fields=+iaS --extra=+q --c-kinds=+p .<CR>
map <F12> :!ctags -R --sort=yes --c++-kinds=+p --fields=+S --c-kinds=+p .<CR><CR>

inoremap <C-Space> <C-x><C-o>
inoremap <Nul> <C-x><C-o>
noremap <Space> za

set tags+=~/.vim/tags/cpp

"let OmniCpp_ShowPrototypeInAbbr=1
"let OmniCpp_MayCompleteDot=1
"let OmniCpp_MayCompleteArrow=1
"let OmniCpp_MayCompleteScope=1

set completeopt=longest,menuone
"menuone,menu,longest

set foldmethod=manual
set foldnestmax=10
set nofoldenable
set foldlevel=1
set nowrap

let mapleader=","
"nnoremap <leader>e :FufCoverageFile<cr>
nnoremap <leader>e :CtrlP<cr>
"nnoremap <leader>b :FufBuffer<cr>
nnoremap <leader>b :CtrlPBuffer<cr>
"nnoremap <leader>d :FufDir<cr>
nnoremap <leader>d :CtrlPDir<cr>
"nnoremap <leader>o :FufFile<cr>
nnoremap <leader>m :CtrlPMRU<cr>
nnoremap <leader>, :b#<cr>
nnoremap <leader>1 :diffget //2<cr>:diffupdate<cr>
nnoremap <leader>3 :diffget //3<cr>:diffupdate<cr>
nnoremap <leader>s :Gstatus<cr>
nnoremap <leader>c :Gcommit<cr>

"nnoremap <leader>w <C-w>k
"nnoremap <leader>s <C-w>j
"nnoremap <leader>a <C-w>h
"nnoremap <leader>d <C-w>l
nnoremap <leader>q <C-w>c

nnoremap <leader>v :vsplit<cr>
inoremap jj <ESC>

"au BufWinLeave *.* mkview
"au BufWinEnter *.* silent loadview

highlight Pmenu ctermbg=grey
highlight PmenuSel ctermfg=black ctermbg=yellow

set laststatus=2 "For powerline
let g:Powerline_symbols='compatible'

let g:vimroom_background="#272822"

set backupdir=$HOME/.vim/swp
set directory=$HOME/.vim/swp

hi CursorLine ctermbg=236 ctermfg=none cterm=none
set cursorline
